global:
  slack_api_url: 'YOUR_SlackWebhookURL'  # Slack webhook URL

route:
  group_by: ['alertname', 'severity']
  receiver: 'slack-notifications'

receivers:
- name: 'slack-notifications'
  slack_configs:
  - channel: '#alerts'
    send_resolved: true
    text: "{{ range .Alerts }}\n*Alert:* {{ .Annotations.summary }}\n*Description:* {{ .Annotations.description }}\n*Details:* {{ .Labels.severity }}\n{{ end }}"
