version: '3'

services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./:/etc/
    command:
      - '--config.file=/etc/prometheus.yml'
    expose:
      - 9090
    ports:
      - 9090:9090 
    extra_hosts:
      - "host.docker.internal:host-gateway"

  node-exporter:
    image: quay.io/prometheus/node-exporter:latest
    container_name: nodeexporter
    ports:
      - 9100:9100
    expose:
      - 9100

  grafana:
    image: grafana/grafana-oss:latest
    container_name: grafana
    ports:
      - 3000:3000
